### ISSUE TITLE
Overall structure

### ISSUE THREAD

**Issue by hzoo** [hzoo/shengji#1]
### Before
- https://github.com/hzoo/Tuolaji-Nonoba
- Flash
- C# Nonoba server (bought by yahoo)
- Put most of the code in 2 files
  - Client: https://github.com/hzoo/Tuolaji-Nonoba/blob/master/Flash/MyGame.as
  - Server: https://github.com/hzoo/Tuolaji-Nonoba/blob/master/Serverside%20Code/Game.cs
- No tests
### What now? Maybe..
- [x] UI: [React](http://facebook.github.io/react/)
  - [x] UI Arch: [Flux](https://facebook.github.io/flux/) or [reflux](https://github.com/spoike/refluxjs)
  - [x] Router: react-router/director
- [x] Build tooling: [webpack](https://webpack.github.io/) + npm + gulp? ~~browserify~~
  - [x] npm: [reacthotloader](https://gaearon.github.io/react-hot-loader/)
- [x] Testing: tape, mocha? ~~/jasmine - karma/chai/sinon~~
- [x] Database: in memory while development then -> ~~Mongo, redis~~
- [x] Server: express, [node](http://nodejs.org/), renderComponentToString (React)
- [x] Client-Server: [socket.io](http://socket.io/)
  - Client verification: message + checksum
- [x] Host: Heroku for development
- [x] CI: Codeship, coveralls, instanbul? ~~Circle CI, Travis CI~~
- [x] Linting: [jshint](http://jshint.com/docs/), [jscs](https://github.com/jscs-dev/node-jscs), jsdoc
- [x] Other: lodash

**Comment by kumquatexpress** [comment]
I think an important design point concerns how much server side communication there should be. The only secure method I can think of is that every hand is stored as a temporary row somewhere and each trick requires a db update. I'm sure there are others, including something where the hands are client only in which case we could use angular.

I'm not familiar with the benefits of different front-end frameworks but they're probably not too different.

As a last note, maybe consider mongo for the architecture since the models aren't that relational and we could just have rows for each player. Mongoose is a decent orm for this option

**Comment by hzoo** [comment]
To prevent some kind of client side cheating - I think we just need to check to see if the state on the client is the same as the server? The players will never be able to see the cards of the other players since they will only be sent their own hand and whatever is being played. 

So checking if the cards they play are actually there, etc. (There is also asking your team mate what their cards are but that's out of scope).

Haha I think I never used a database with the old one - it probably was all in memory or something and each game instance was separate. If we do use a db then yeah we will need to update it each action - can use redis as well if we don't need queries

**Comment by kumquatexpress** [comment]
Hmm, I think if we want to keep it simple, just going with a serverside in memory model would be easiest. It's basically the same as redis without the extra later on top.

If we want to have better tracking though, having a dedicated db would be the way to go. Examples are like game stats, most played card, most points won, most points in a row, etc.

**Comment by bitnovus** [comment]
If we need to verify the correctness of the client state against the server state, we can send a checksum with the message from the client.

Once development finishes, Heroku will likely not be the best host because of their slow start-up time after idling and also because their costs rise extremely rapidly. I strongly suggest either using a VPS like DigitalOcean or find something like GCE for Node (Nodejitsu?).

**Comment by kumquatexpress** [comment]
Well heroku is never a long-term solution for any project, deployment of a small node app is extremely easy on anything though since npm takes care of everything. 

I do think we should come up with a data model that we use to represent each card at the start so that we don't end up making the model bloated later on. Cards being their own dedicated objects would be optimal.

**Comment by hzoo** [comment]
For the data model - maybe check #3, or we can make a separate issue for that. (I made Cards just objects that have a value and suit).
